version: '2.1'
services:
    php:
        container_name: php
        image: php:7.0-fpm
        build: ./docker/php
        links:
            - mysql
        ports:
            - "9000"
        expose:
            - "9000"
        volumes:
            - ./api:/var/www/html

    api:
        image: nginx:latest
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./api:/var/www/html
            - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        links:
            - php
        volumes_from:
            - php
        working_dir: /var/www/html
        depends_on:
            - php

    client:
        image: nginx:latest
        ports:
            - "3000:80"
        volumes:
            - ./client:/var/www/html
            - ./docker/nginx/client.conf:/etc/nginx/conf.d/default.conf

    mysql:
        image: mysql:latest
        volumes_from:
            - data
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user

    data:
        image: mysql:latest
        volumes:
            - /var/lib/mysql
            - ./api/database.sql:/docker-entrypoint-initdb.d/database.sql
        command: "true"
